apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: workflows
type: Opaque
data:
  token: Z2hwX1lETTZwWFRpQWlhczdPWGJtbEhGWmZBUTh4bWdRMjNJNjJZVg==
  user: amVua2lucy14LXNldHVw
  email: bmlhemh1c3NlaW4xOTkwQGdtYWlsLmNvbQ==
